id: P001665
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W30431
  title: བྱ་ཚིག་ཀུན་གསལ་མེ་ལོང
  author: ''
  volumes:
    db700822130a400e93b452cea58e196e:
      image_group_id: I1PD30289
      title: ''
      volume_number: 1
      total_pages: 530
      base_file: v001.txt
